@url=http://localhost:3000/users


### CRIAR
POST {{url}}
Content-Type: application/json

{
    "name": "Juca",
    "email": "j@gmail.com",
    "password": "1234",
    "birth": "2000-01-01"
}

### GET ALL
GET {{url}}

### GET by id
GET {{url}}/6628f5166ecd4a0c2f0cac43


